server:
    port: 8080
spring:
    profiles.active: development
---
spring:
    profiles: development
    datasource:
        driverClassName: org.hsqldb.jdbc.JDBCDriver
        url: jdbc:hsqldb:mem:codecraft_dev
        username: sa
        password:
    jpa:
        open-in-view: true
        show-sql: true
        hibernate:
            ddl-auto: update
---
spring:
    profiles: production
    datasource:
        driverClassName: org.hsqldb.jdbc.JDBCDriver
        url: jdbc:hsqldb:mem:codecraft_prod
        username: sa
        password:
    jpa:
        open-in-view: true
        show-sql: false
        hibernate:
            ddl-auto: update